# Generated by Django 4.2.4 on 2023-10-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_learning_description_and_more'),
        ('courses', '0005_alter_course_slug'),
    ]

    operations = [
    ]
